# Generated by Django 3.1.6 on 2021-02-10 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('playlist', models.CharField(choices=[('C', 'Country'), ('R', 'Rock'), ('P', 'Pop'), ('H', 'HipHop'), ('M', 'Melody')], default='C', max_length=1)),
                ('tune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tune')),
            ],
        ),
    ]
