# Generated by Django 3.1.6 on 2021-02-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='instruments',
            field=models.ManyToManyField(to='main_app.Instrument'),
        ),
    ]
